title: More Dimensions
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for   Google search results) and in your feed.xml site description.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

# Collections
collections:
  banners:
    output: true
    permalink: /banners/:path.html

  teasers:
    output: true
    permalink: /teasers/:path.html

  news:
    output: true
    permalink: /news/:path.html

